project_id = "ozukfrksvwaqmmsdmlbu"

[functions.ai-chat]
verify_jwt = true

[functions.fapshi-webhook]
verify_jwt = false

[functions.exam-start]
verify_jwt = true

[functions.exam-submit]
verify_jwt = true

[functions.import-questions]
verify_jwt = true